{
 "title": "NUT Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(nut_device_info, instance)"
   },
   {
    "name": "nut_server",
    "label": "NUT Server",
    "query": "label_values(nut_device_info{instance=\"$instance\"}, nut_server)"
   },
   {
    "name": "ups",
    "label": "UPS",
    "query": "label_values(nut_device_info{instance=\"$instance\", nut_server=\"$nut_server\"}, ups)"
   }
  ]
 },
 "panels": [
  {
   "title": "Estimated Wattage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "((nut_ups_realpower_nominal_watts{instance=\"$instance\", nut_server=\"$nut_server\", ups=\"$ups\"} * nut_ups_load_percent{instance=\"$instance\", nut_server=\"$nut_server\", ups=\"$ups\"})/100)"
    }
   ]
  },
  {
   "title": "Battery Charge Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_battery_charge_percent{instance=\"$instance\", nut_server=\"$nut_server\", ups=\"$ups\"}\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nut_battery_voltage_volts{instance=\"$instance\", nut_server=\"$nut_server\", ups=\"$ups\"}"
    },
    {
     "expr": "nut_battery_voltage_nominal_volts{instance=\"$instance\", nut_server=\"$nut_server\", ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nut_input_voltage_volts{instance=\"$instance\", nut_server=\"$nut_server\", ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Estimated Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime_seconds{instance=\"$instance\", nut_server=\"$nut_server\", ups=\"$ups\"}/60"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_ups_load_percent{instance=\"$instance\", nut_server=\"$nut_server\", ups=\"$ups\"}"
    }
   ]
  }
 ]
}